### ISSUE TITLE
Since symfony/workflow 6.4: The Symfony\Component\Workflow\Event\GuardEvent::getContext() method is deprecated and will be removed in 7.0

### ISSUE THREAD

**Issue by amarmain** [zerodahero/laravel-workflow#89] opened 2023-12-07 11:08 UTC
Version : 4.2.0

I get this deprecate error while using the last version of the package:

`Since symfony/workflow 6.4: The Symfony\Component\Workflow\Event\GuardEvent::getContext() method is deprecated and will be removed in 7.0. You should no longer call this method as it always returns an empty array when invoked within a guard listener. in /vendor/symfony/deprecation-contracts/function.php on line 25`

How can I prevent it please?

**Comment by zerodahero** [comment] 2023-12-07 14:10
Looks like we're going to need to do some work to support Symfony 7 (and clear up these warnings in the meantime). A quick glance at the code suggests the issue is in the helper methods in (de)serialization, [here](https://github.com/zerodahero/laravel-workflow/blob/develop/src/Events/BaseEvent.php#L45).

Seems like the best/easiest route right now is to make the `BaseEvent` class context-less (i.e. don't call `->getContext()` on the base event) and then either with a trait or intermediate class, reintroduce that to the non-guard events.

We should definitely look through the rest of the Symfony 7 changes to see what else is special with guard listener events. It may be worth splitting those off entirely.

PRs are greatly appreciated here! I don't expect to be able to find the time to take care of this in the near future (I'm not really using PHP nowadays anymore either).

**Comment by zerodahero** [comment] 2024-04-15 01:21
Fixed with v5: https://github.com/zerodahero/laravel-workflow/releases/tag/v5.0.0

**Closed as completed by zerodahero** 2024-04-15 01:21 UTC
Labels: help wanted
