### ISSUE TITLE
Wrong behavior when having multiple "from" places in transaction

### ISSUE THREAD

**Issue by PavelTytyuk** [zerodahero/laravel-workflow#26] opened 2020-08-12 19:09 UTC
While trying to recreate [this example](https://symfony-workflow-demo.herokuapp.com/article) I run into a weird behavior:

### Workflow definition

```php 

    'test' => [
        'type' => 'workflow', // or 'state_machine'
        'marking_store' => [
            'type' => 'multiple_state', // or 'single_state'
            'property' => 'delivery_workflow', // this is the property on the model
        ],
        'supports' => ['App\Booking\Trip'],
        'places' => ['draft', 'waiting for journalist', 'approved by journalist', 'wait for spellchecker', 'approved by spellchecker', 'published'],
        'transitions' => [
            'request review' => [
                'from' => 'draft',
                'to' => ['waiting for journalist', 'wait for spellchecker']
            ],
            'journalist approval' => [
                'from' => 'waiting for journalist',
                'to' => 'approved by journalist'
            ],
            'spellchecker approval' => [
                'from' => 'wait for spellchecker',
                'to' => 'approved by spellchecker'
            ],
            'publish' => [
                'from' => ['approved by journalist', 'approved by spellchecker'],
                'to' => 'published'
            ],
        ],
    ],
```

### Expected
![Screenshot from 2020-08-12 21-58-31](https://user-images.githubusercontent.com/50485/90056331-5e8bd580-dce7-11ea-96f2-3baf273fb926.png)
### Fact (publish transition rendered twice)
![Screenshot from 2020-08-12 21-58-24](https://user-images.githubusercontent.com/50485/90056334-5f246c00-dce7-11ea-84ad-667b61e29178.png)

After quick digging I found that it happens in [WorkflowRegistry](https://github.com/zerodahero/laravel-workflow/blob/fc5b1888f177d1c093afcdd87d03e5fa207d345e/src/WorkflowRegistry.php#L218)

Instead of simple
```php
            $transitionObj = new Transition($transitionName, $transition['from'], $transition['to']);
            $builder->addTransition($transitionObj);
```
we can see this:
```php
            foreach ((array)$transition['from'] as $form) {  // 
                $transitionObj = new Transition($transitionName, $form, $transition['to']);
                $builder->addTransition($transitionObj);

                if (isset($transition['metadata'])) {
                    $metadata['transitions']->attach($transitionObj, $transition['metadata']);
                }
            }
```
I believe this was done on purpose, but it doesn't look right. What's the back thinking behind this?

**Comment by zerodahero** [comment] 2020-08-13 00:38
Hmmm, not quite sure. This looks like a carry-over from an earlier version of this package. Looks like the tricky part here is defining (via assoc. array in config) whether a transition should go from multiple places to one, or whether two different places can both transition to that place.

Do you have any suggestions on addressing that? Looks like the Symfony Transition class will handle an array `$from` (lol at the misspelling in source). My first thought would be treating the "top" level of the 'from' array in the config as the "places" and allow arrays in it. So, your diagram example would be:

```
// ...
'transitions' => [
            'publish' => [
                'from' => [
                   ['approved_by_journalist', 'approved_by_spellchecker']
                ]
                'to' => 'published'
            ],
// ...
```

Which, looking at the code, that may already support that, though it's not documented anywhere?

**Comment by PavelTytyuk** [comment] 2020-08-13 07:11
Symfony really supports arrays in `$from`, and, I believe, been doing so since early workflow component versions.

I have already applied the code I mentioned in first snippet. Instead of foreach:
```php
            $transitionObj = new Transition($transitionName, $transition['from'], $transition['to']);
            $builder->addTransition($transitionObj);

            if (isset($transition['metadata'])) {
                $metadata['transitions']->attach($transitionObj, $transition['metadata']);
            }
```
And the diagram looks this way:
```
            'publish' => [
                'from' => ['approved by journalist', 'approved by spellchecker'],
                'to' => 'published'
            ],
```

Don't see any reason to add another level to 'from' and treat it any different from 'to'. [Original YAML config](https://github.com/lyrixx/SFLive-Paris2016-Workflow/blob/master/config/packages/workflow.yaml#L49)  is a plain array:
```yaml
                publish:
                    guard: "is_fully_authenticated()"
                    from:
                        - approved by journalist
                        - approved by spellchecker
                    to: published
```

**Comment by zerodahero** [comment] 2020-08-13 13:14
Yes, that's right. The Transition class has supported arrays since at least 3.0, but I'm not sure the YAML has. I'll have to take a closer look into how Symfony handles it (that's the biggest divergence between this package and Symfony). The issue is how to differentiate between (a) either Place1 OR Place2 can transition to Place3 and (b) BOTH Place1 AND Place2 transition to Place3.

**Comment by zerodahero** [comment] 2020-08-19 17:53
I'm going to close this for now, in favor of adding this into the documentation. There may be some possible routes to explore in the future with changing this behavior based on the workflow type (state machine or workflow), though I'm not quite sure how we could make the right assumptions to keep the config as is.

Please let me know if I'm misunderstanding anything here and we can reopen this.

**Closed as completed by zerodahero** 2020-08-19 17:53 UTC
